/**
 * نامِ فارسیِ فیلدها و مقدارهای شمارشی در جزئیاتِ رویداد.
 *
 * ⚠️ این متن‌ها از راهِ متغیر به `tr()` می‌رسند و استخراج‌گرِ ترجمه نمی‌بیندشان؛
 * هر کلیدِ تازه باید دستی به فایل‌های زبان اضافه شود (`scripts/i18n-merge.mjs`).
 * فیلدِ بی‌نام نامِ فنی‌اش را نشان می‌دهد — بهتر از پنهان‌شدنِ تغییر.
 */
export const FIELD_LABELS: Record<string, string> = {
  value: 'مقدار',

  // فرد و حساب
  name: 'نام',
  email: 'ایمیل',
  phone: 'تلفن',
  username: 'نامِ کاربری',
  privateAccess: 'دسترسیِ خصوصی',
  tagIds: 'نقش‌ها',
  officeIds: 'دفترها',
  managedOfficeIds: 'دفترهای تحتِ مدیریت',
  memberState: 'حالتِ عضو',
  locale: 'زبان',
  timezone: 'منطقهٔ زمانی',
  role: 'نقش',
  hasPassword: 'رمز تعیین شد',
  hasBank: 'اطلاعاتِ بانکی دارد',
  changed: 'تغییر کرد',
  alreadyHad: 'از پیش داشت',
  isNew: 'کاربرِ تازه',
  sent: 'ایمیل فرستاده شد',
  userId: 'فرد',

  // پروژه و تسک
  title: 'عنوان',
  description: 'توضیح',
  deadline: 'ددلاین',
  regDate: 'تاریخِ ثبت',
  price: 'مبلغِ پروژه',
  currencyId: 'ارز',
  officeId: 'دفتر',
  parentId: 'پروژهٔ مادر',
  statusTagId: 'وضعیت',
  isTender: 'مناقصه‌ای',
  tenderRoles: 'نقش‌های مناقصه',
  isUnitBased: 'تعدادی',
  isArchived: 'بایگانی',
  thumbnailFileId: 'تصویرِ شاخص',
  lightenSummary: 'خلاصهٔ سبک‌سازی',
  projectId: 'پروژه',
  members: 'اعضا',
  clientIds: 'کارفرمایان',
  assignedTo: 'مسئول',
  createdBy: 'سازنده',
  dependsOn: 'وابسته به',
  dueDate: 'سررسید',
  isPrivate: 'خصوصی',
  priorityTagId: 'اولویت',
  roleTagId: 'نقش',
  roleTagIds: 'نقش‌ها',
  taskId: 'تسک',
  taskIds: 'تسک‌ها',
  plan: 'جزئیات',
  length: 'طولِ متن (نویسه)',
  status: 'وضعیت',
  isDone: 'انجام شده',
  audiences: 'مخاطبان',
  added: 'افزوده‌شده',
  tasks: 'تسک‌ها',
  from: 'از',
  to: 'تا',
  note: 'یادداشت',

  // مالی
  accountId: 'حساب',
  amount: 'مبلغ',
  amountSettled: 'مبلغِ تسویه',
  amountAccountOverride: 'مبلغ به ارزِ حساب',
  settledCurrencyId: 'ارزِ تسویه',
  billable: 'قابلِ صورت‌حساب',
  categoryTagId: 'دسته',
  computed: 'محاسبه‌شده',
  direction: 'جهت',
  entryDate: 'تاریخ',
  fxRate: 'نرخِ تبدیل',
  payerLabel: 'پرداخت‌کننده',
  payerUserId: 'پرداخت‌کننده (فرد)',
  receiverLabel: 'دریافت‌کننده',
  receiverUserId: 'دریافت‌کننده (فرد)',
  addedReceiptIds: 'رسیدهای افزوده',
  removedReceiptIds: 'رسیدهای برداشته',
  ledgerId: 'ردیفِ دفتر',
  transferGroup: 'گروهِ انتقال',
  ids: 'ردیف‌ها',
  group: 'گروهِ انتقال',
  closeDate: 'تاریخِ بستن',
  lockDate: 'تاریخِ قفل',
  accounts: 'تعدادِ حساب‌ها',
  ledger: 'ردیف‌های دفتر',
  payments: 'پرداخت‌ها',
  quantity: 'تعداد',
  entryId: 'کارکرد',
  result: 'نتیجه',
  nextDueDate: 'سررسیدِ بعدی',
  after: 'سررسیدِ بعدی',
  vendorId: 'طرف‌حساب',
  kind: 'نوع',
  intervalUnit: 'واحدِ دوره',
  intervalCount: 'طولِ دوره',
  startDate: 'تاریخِ شروع',
  isActive: 'فعال',
  type: 'نوع',
  openingBalance: 'ماندهٔ آغازین',

  // شرکت و تنظیمات
  address: 'نشانی',
  bank: 'اطلاعاتِ بانکیِ شرکت',
  invoiceFooter: 'پانویسِ فاکتور',
  taxId: 'شناسهٔ مالیاتی',
  website: 'وب‌سایت',
  code: 'کد',
  symbol: 'نماد',
  decimals: 'رقم‌های اعشار',
  isDefault: 'پیش‌فرض',
  rate: 'نرخ',
  fromCurrencyId: 'از ارز',
  toCurrencyId: 'به ارز',
  color: 'رنگ',
  location: 'محل',
  defaultCurrencyId: 'ارزِ پیش‌فرض',
  brandName: 'نامِ برند',
  chatPollEnabled: 'گفتگوی زنده',
  chatPollInterval: 'فاصلهٔ به‌روزرسانیِ گفتگو (ثانیه)',
  defaultLocale: 'زبانِ پیش‌فرض',
  msgPurgeDays: 'پاک‌سازیِ پیام‌ها (روز)',
  onboardingEnabled: 'آنبوردینگ',
  ownerTeamView: 'نمای تیمیِ مالک',
  presenceEnabled: 'نمایشِ حضور',
  presenceIdle: 'بی‌کار پس از (دقیقه)',
  presenceOffline: 'آفلاین پس از (دقیقه)',
  presencePing: 'فاصلهٔ اعلامِ حضور (ثانیه)',
  pulseEnabled: 'نبضِ صفحه',
  pulseInterval: 'فاصلهٔ نبض (ثانیه)',
  weekStart: 'آغازِ هفته',

  // جلسه و ساعت
  meetAt: 'زمانِ جلسه',
  meetingScope: 'دامنهٔ جلسه',
  attendeeIds: 'شرکت‌کنندگان',
  logDate: 'تاریخ',
  minutes: 'مدت (دقیقه)',
  hours: 'ساعت',

  // دسترسی‌ها و آنبوردینگ
  serviceId: 'سرویس',
  level: 'سطحِ دسترسی',
  accountRef: 'شناسهٔ حساب در سرویس',
  vaultRef: 'جای نگه‌داریِ رمز',
  adminUrl: 'نشانیِ مدیریت',
  ownerUserId: 'مسئول',
  via: 'از راهِ',
  link: 'پیوند',
  dueDay: 'روزِ موعد',
  assignee: 'انجام‌دهنده',
  assigneeUserId: 'انجام‌دهنده (فرد)',

  // پشتیبان
  enabled: 'فعال',
  hour: 'ساعتِ اجرا',
  passphraseChanged: 'عبارتِ رمزِ پشتیبان عوض شد',
  file: 'فایل',
  trigger: 'آغازگر',
  ok: 'موفق',
  error: 'خطا',
};

/** برچسبِ مقدارهای شمارشی — بر پایهٔ نامِ فیلد. */
export const VALUE_LABELS: Record<string, Record<string, string>> = {
  memberState: { active: 'فعال', finance: 'عضوِ سابق (فقط مالی)', locked: 'قطعِ کاملِ دسترسی' },
  direction: { in: 'دریافت', out: 'پرداخت' },
  role: { owner: 'مالک', admin: 'ادمین', finance: 'مدیرِ مالی', member: 'عضو', client: 'کارفرما' },
  level: { admin: 'مدیر', member: 'کاربر', viewer: 'فقط دیدن' },
  intervalUnit: { day: 'روز', week: 'هفته', month: 'ماه', year: 'سال' },
  status: {
    pending: 'در انتظار', approved: 'تأییدشده', rejected: 'ردشده', paid: 'پرداخت‌شده',
    archived: 'بایگانی‌شده', withdrawn: 'پس‌گرفته', cancelled: 'لغوشده',
    needs_review: 'نیاز به بررسی', done: 'انجام شد',
  },
  trigger: { manual: 'دستی', schedule: 'زمان‌بندی', cli: 'خطِ فرمان' },
};
